# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
